version: "1.0"

stages:
  - clone
  - prepare
  - build
  - unit-test
  - deploy

steps:
  #  Clone stage
  main_clone:
    title: Cloning main repository...
    stage: "clone"
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'

  #  Prepare stage
  check-copyright:
    image: r.cfcr.io/openbanking/ob-release:latest
    stage: "prepare"
    title: "Verify copyrights"
    working-directory: ${{main_clone}}
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository license:check
  # Build stage
  build-stage:
    stage: "build"
    image: r.cfcr.io/openbanking/ob-release:latest
    title: "Compile, build and install artifact"
    working-directory: ${{main_clone}}
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository -Ddockerfile.skip -DdockerCompose.skip -DskipTests -DskipITs clean install -T 8

  # test stage
  test-stage:
    stage: "unit-test"
    image: r.cfcr.io/openbanking/ob-release:latest
    title: "Run unit tests"
    working-directory: ${{main_clone}}
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository -DdockerCompose.skip -Ddockerfile.skip -DskipITs verify

  disable-include-administrator:
    title: "temporarily disable include administrators"
    stage: "deploy"
    image: benjjefferies/branch-protection-bot
    environment:
      - ACCESS_TOKEN=${{GITHUB_ACCESS_TOKEN}}
      - OWNER=${{CF_REPO_OWNER}}
      - REPO=${{CF_REPO_NAME}}
    when:
      condition:
        all:
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "[maven-release-plugin]") == false'
          masterBranch: '"${{CF_BRANCH}}" == "master"'

 # deploy jar stage
  deploy-master:
    title: "deploy jars to private maven repo"
    stage: "deploy"
    image: r.cfcr.io/openbanking/ob-release:latest
    commands:
      - git checkout $CF_BRANCH
      - git reset --hard origin/$CF_BRANCH
      - release.sh /codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository
    environment:
      - GITHUB_GPG_KEY_ID=${{GITHUB_GPG_KEY_ID}}
      - GITHUB_GPG_KEY=${{GITHUB_GPG_KEY}}
      - GITHUB_ACCESS_TOKEN=${{GITHUB_ACCESS_TOKEN}}
      - FR_PRIVATE_REPO_USER=${{FR_PRIVATE_REPO_USER}}
      - FR_PRIVATE_REPO_PASSWORD=${{FR_PRIVATE_REPO_PASSWORD}}
    when:
      condition:
        all:
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "[maven-release-plugin]") == false'
          masterBranch: '"${{CF_BRANCH}}" == "master"'

  enable-include-administrator:
    title: "enable include administrators"
    stage: "deploy"
    image: benjjefferies/branch-protection-bot
    environment:
      - ACCESS_TOKEN=${{GITHUB_ACCESS_TOKEN}}
      - OWNER=${{CF_REPO_OWNER}}
      - REPO=${{CF_REPO_NAME}}
    when:
      condition:
        all:
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "[maven-release-plugin]") == false'
          masterBranch: '"${{CF_BRANCH}}" == "master"'