{
  "swagger": "2.0",
  "info": {
    "description": "Swagger for Payment initiation and Account information APIs Specification",
    "title": "Payment initiation and Account information APIs Specification",
    "termsOfService": "https://backstage.forgerock.com/knowledge/openbanking/article/a45894685",
    "contact": {
      "name": "ForgeRock AS",
      "url": "https://master.forgerock.financial",
      "email": "openbanking-support@forgerock.com"
    },
    "license": { "name": "open-licence", "url": "https://www.openbanking.org.uk/open-licence" }
  },
  "host": "rs.aspsp.master.forgerock.financial",
  "basePath": "/",
  "tags": [
    { "name": "Discovery", "description": "the discovery API" },
    { "name": "MtlsTest", "description": "Test your MTLS setup" },
    { "name": "callback-url-api-controller", "description": "the event notification callback urls API" },
    { "name": "domestic-payment-consents-api-controller", "description": "the domestic-payment-consents API" },
    { "name": "domestic-payments-api-controller", "description": "the domestic-payments API" },
    {
      "name": "domestic-scheduled-payment-consents-api-controller",
      "description": "the domestic-scheduled-payment-consents API"
    },
    { "name": "domestic-scheduled-payments-api-controller", "description": "the domestic-scheduled-payments API" },
    {
      "name": "domestic-standing-order-consents-api-controller",
      "description": "the domestic-standing-order-consents API"
    },
    { "name": "domestic-standing-orders-api-controller", "description": "the domestic-standing-orders API" },
    { "name": "errors-api-controller", "description": "Errors Api Controller" },
    { "name": "file-payment-consents-api-controller", "description": "the file-payment-consents API" },
    { "name": "file-payments-api-controller", "description": "the file-payments API" },
    { "name": "funds-confirmation-api-controller", "description": "the funds-confirmation API" },
    { "name": "funds-confirmation-consents-api-controller", "description": "the funds-confirmation-consents API" },
    {
      "name": "international-payment-consents-api-controller",
      "description": "the international-payment-consents API"
    },
    { "name": "international-payments-api-controller", "description": "the international-payments API" },
    {
      "name": "international-scheduled-payment-consents-api-controller",
      "description": "the international-scheduled-payment-consents API"
    },
    {
      "name": "international-scheduled-payments-api-controller",
      "description": "the international-scheduled-payments API"
    },
    {
      "name": "international-standing-order-consents-api-controller",
      "description": "the international-standing-order-consents API"
    },
    { "name": "international-standing-orders-api-controller", "description": "the international-standing-orders API" },
    { "name": "jwk", "description": "the RS JWK API" },
    { "name": "v1.1-AccountRequests", "description": "the account-requests API" },
    { "name": "v1.1-Accounts", "description": "the accounts API" },
    { "name": "v1.1-Balances", "description": "the balances API" },
    { "name": "v1.1-Beneficiaries", "description": "the beneficiaries API" },
    { "name": "v1.1-Direct-Debits", "description": "the direct-debits API" },
    { "name": "v1.1-Payments", "description": "the payment-submissions API" },
    { "name": "v1.1-Products", "description": "the products API" },
    { "name": "v1.1-Standing-Orders", "description": "the standing-orders API" },
    { "name": "v1.1-Transactions", "description": "the transactions API" },
    { "name": "v2.0-Account-Requests", "description": "the account-requests API" },
    { "name": "v2.0-Accounts", "description": "the accounts API" },
    { "name": "v2.0-Balances", "description": "the balances API" },
    { "name": "v2.0-Beneficiaries", "description": "the beneficiaries API" },
    { "name": "v2.0-Direct-Debits", "description": "the direct-debits API" },
    { "name": "v2.0-Offers", "description": "the offers API" },
    { "name": "v2.0-Party", "description": "the party API" },
    { "name": "v2.0-Payments", "description": "the payment-submissions API" },
    { "name": "v2.0-Products", "description": "the products API" },
    { "name": "v2.0-Scheduled-Payments", "description": "the scheduled-payments API" },
    { "name": "v2.0-Standing-Orders", "description": "the standing-orders API" },
    { "name": "v2.0-Statements", "description": "the statements API" },
    { "name": "v2.0-Transactions", "description": "the transactions API" },
    { "name": "v3.0-Accounts", "description": "the accounts API" },
    { "name": "v3.0-Balances", "description": "the balances API" },
    { "name": "v3.0-Beneficiaries", "description": "the beneficiaries API" },
    { "name": "v3.0-Direct-Debits", "description": "the direct-debits API" },
    { "name": "v3.0-Offers", "description": "the offers API" },
    { "name": "v3.0-Party", "description": "the party API" },
    { "name": "v3.0-Products", "description": "the products API" },
    { "name": "v3.0-Scheduled-Payments", "description": "the scheduled-payments API" },
    { "name": "v3.0-Standing-Orders", "description": "the standing-orders API" },
    { "name": "v3.0-Statements", "description": "the statements API" },
    { "name": "v3.0-Transactions", "description": "the transactions API" },
    { "name": "v3.0-account-access-consents", "description": "the account-access-consents API" },
    { "name": "v3.1-Accounts", "description": "the accounts API" },
    { "name": "v3.1-Balances", "description": "the balances API" },
    { "name": "v3.1-Beneficiaries", "description": "the beneficiaries API" },
    { "name": "v3.1-Direct-Debits", "description": "the direct-debits API" },
    { "name": "v3.1-Offers", "description": "the offers API" },
    { "name": "v3.1-Party", "description": "the party API" },
    { "name": "v3.1-Products", "description": "the products API" },
    { "name": "v3.1-Scheduled-Payments", "description": "the scheduled-payments API" },
    { "name": "v3.1-Standing-Orders", "description": "the standing-orders API" },
    { "name": "v3.1-Statements", "description": "the statements API" },
    { "name": "v3.1-Transactions", "description": "the transactions API" },
    { "name": "v3.1-account-access-consents", "description": "the account-access-consents API" }
  ],
  "paths": {
    "/api/jwk/jwk_uri": {
      "get": {
        "tags": ["jwk"],
        "summary": "Get JWK URI",
        "description": "Get the public keys in JWK format",
        "operationId": "jwksUriUsingGET",
        "deprecated": false
      }
    },
    "/open-banking/api/errors/": {
      "get": {
        "tags": ["errors-api-controller"],
        "summary": "getAllErrorTypes",
        "operationId": "getAllErrorTypesUsingGET",
        "deprecated": false
      }
    },
    "/open-banking/discovery": {
      "get": {
        "tags": ["Discovery"],
        "summary": "Discover the RS api",
        "description": "Get all the endpoints you need to consume the RS API",
        "operationId": "discoveryUsingGET",
        "deprecated": false
      }
    },
    "/open-banking/mtlsTest": {
      "get": {
        "tags": ["MtlsTest"],
        "summary": "Test your MATLS setup",
        "description": "The idea is that you attach your client certificates to the request, and this endpoint will tell you who you are, based on this certificate",
        "operationId": "mtlsTestUsingGET",
        "deprecated": false
      }
    },
    "/open-banking/v1.1/account-requests": {
      "post": {
        "tags": ["v1.1-AccountRequests"],
        "summary": "Create an account request",
        "description": "Create an account request",
        "operationId": "createAccountRequestUsingPOST_1",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/account-requests/{AccountRequestId}": {
      "get": {
        "tags": ["v1.1-AccountRequests"],
        "summary": "Get an account request",
        "description": "Get an account request",
        "operationId": "getAccountRequestUsingGET_1",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      },
      "delete": {
        "tags": ["v1.1-AccountRequests"],
        "summary": "Delete an account request",
        "description": "Delete an account request",
        "operationId": "deleteAccountRequestUsingDELETE_1",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/accounts": {
      "get": {
        "tags": ["v1.1-Accounts"],
        "summary": "Get Accounts",
        "description": "Get a list of accounts",
        "operationId": "getAccountsUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/accounts/{AccountId}": {
      "get": {
        "tags": ["v1.1-Accounts"],
        "summary": "Get Account",
        "description": "Get an account",
        "operationId": "getAccountUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/accounts/{AccountId}/balances": {
      "get": {
        "tags": ["v1.1-Balances"],
        "summary": "Get Account Balances",
        "description": "Get Balances related to an account",
        "operationId": "getAccountBalancesUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/accounts/{AccountId}/beneficiaries": {
      "get": {
        "tags": ["v1.1-Beneficiaries"],
        "summary": "Get Account Beneficiaries",
        "description": "Get Beneficiaries related to an account",
        "operationId": "getAccountBeneficiariesUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/accounts/{AccountId}/direct-debits": {
      "get": {
        "tags": ["v1.1-Direct-Debits"],
        "summary": "Get Account Direct Debits",
        "description": "Get Direct Debits related to an account",
        "operationId": "getAccountDirectDebitsUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/accounts/{AccountId}/product": {
      "get": {
        "tags": ["v1.1-Products"],
        "summary": "Get Account Product",
        "description": "Get Product related to an account",
        "operationId": "getAccountProductUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/accounts/{AccountId}/standing-orders": {
      "get": {
        "tags": ["v1.1-Standing-Orders"],
        "summary": "Get Account Standing Orders",
        "description": "Get Standing Orders related to an account",
        "operationId": "getAccountStandingOrdersUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/accounts/{AccountId}/transactions": {
      "get": {
        "tags": ["v1.1-Transactions"],
        "summary": "Get Account Transactions",
        "description": "Get transactions related to an account",
        "operationId": "getAccountTransactionsUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/balances": {
      "get": {
        "tags": ["v1.1-Balances"],
        "summary": "Get Balances",
        "description": "Get Balances",
        "operationId": "getBalancesUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/beneficiaries": {
      "get": {
        "tags": ["v1.1-Beneficiaries"],
        "summary": "Get Beneficiaries",
        "description": "Get Beneficiaries",
        "operationId": "getBeneficiariesUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/direct-debits": {
      "get": {
        "tags": ["v1.1-Direct-Debits"],
        "summary": "Get Direct Debits",
        "description": "Get Direct Debits",
        "operationId": "getDirectDebitsUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/payment-submissions": {
      "post": {
        "tags": ["v1.1-Payments"],
        "summary": "Create a payment submission",
        "description": "Submit a previously setup payment",
        "operationId": "createPaymentSubmissionUsingPOST_1",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/payment-submissions/{PaymentSubmissionId}": {
      "get": {
        "tags": ["v1.1-Payments"],
        "summary": "Get a payment submission",
        "description": "Get payment submission",
        "operationId": "getPaymentSubmissionUsingGET_1",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }, { "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/payments": {
      "post": {
        "tags": ["v1.1-Payments"],
        "summary": "Create a single immediate payment",
        "description": "Create a single immediate payment",
        "operationId": "createSingleImmediatePaymentUsingPOST",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/payments/{PaymentId}": {
      "get": {
        "tags": ["v1.1-Payments"],
        "summary": "Get a single immediate payment",
        "description": "Get a single immediate payment",
        "operationId": "getSingleImmediatePaymentUsingGET",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }, { "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/products": {
      "get": {
        "tags": ["v1.1-Products"],
        "summary": "Get Products",
        "description": "Get Products",
        "operationId": "getProductsUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/standing-orders": {
      "get": {
        "tags": ["v1.1-Standing-Orders"],
        "summary": "Get Standing Orders",
        "description": "Get Standing Orders",
        "operationId": "getStandingOrdersUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v1.1/transactions": {
      "get": {
        "tags": ["v1.1-Transactions"],
        "summary": "Get Transactions",
        "description": "Get Transactions",
        "operationId": "getTransactionsUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/account-requests": {
      "post": {
        "tags": ["v2.0-Account-Requests"],
        "summary": "Create an account request",
        "description": "Create an account request",
        "operationId": "createAccountRequestUsingPOST",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/account-requests/{AccountRequestId}": {
      "get": {
        "tags": ["v2.0-Account-Requests"],
        "summary": "Get an account request",
        "description": "Get an account request",
        "operationId": "getAccountRequestUsingGET",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      },
      "delete": {
        "tags": ["v2.0-Account-Requests"],
        "summary": "Delete an account request",
        "description": "Delete an account request",
        "operationId": "deleteAccountRequestUsingDELETE",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts": {
      "get": {
        "tags": ["v2.0-Accounts"],
        "summary": "Get Accounts",
        "description": "Get a list of accounts",
        "operationId": "getAccountsUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}": {
      "get": {
        "tags": ["v2.0-Accounts"],
        "summary": "Get Account",
        "description": "Get an account",
        "operationId": "getAccountUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/balances": {
      "get": {
        "tags": ["v1.1-Balances", "v2.0-Balances"],
        "summary": "Get Account Balances",
        "description": "Get Balances related to an account",
        "operationId": "getAccountBalancesUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/beneficiaries": {
      "get": {
        "tags": ["v2.0-Beneficiaries"],
        "summary": "Get Account Beneficiaries",
        "description": "Get Beneficiaries related to an account",
        "operationId": "getAccountBeneficiariesUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/direct-debits": {
      "get": {
        "tags": ["v1.1-Direct-Debits", "v2.0-Direct-Debits"],
        "summary": "Get Account Direct Debits",
        "description": "Get Direct Debits related to an account",
        "operationId": "getAccountDirectDebitsUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/offers": {
      "get": {
        "tags": ["v2.0-Offers"],
        "summary": "Get Account Offers",
        "description": "Get Offers related to an account",
        "operationId": "getAccountOffers_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/party": {
      "get": {
        "tags": ["v2.0-Party"],
        "summary": "Get Account Party",
        "description": "Get Party related to an account",
        "operationId": "getAccountParty_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/product": {
      "get": {
        "tags": ["v2.0-Products"],
        "summary": "Get Account Product",
        "description": "Get Product related to an account",
        "operationId": "getAccountProductUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/scheduled-payments": {
      "get": {
        "tags": ["v2.0-Scheduled-Payments"],
        "summary": "Get Account Scheduled Payments",
        "description": "Get Scheduled Payments related to an account",
        "operationId": "getAccountScheduledPayments_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/standing-orders": {
      "get": {
        "tags": ["v2.0-Standing-Orders"],
        "summary": "Get Account Standing Orders",
        "description": "Get Standing Orders related to an account",
        "operationId": "getAccountStandingOrdersUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/statements": {
      "get": {
        "tags": ["v2.0-Statements"],
        "summary": "Get Account Statements",
        "description": "Get Statements related to an account",
        "operationId": "getAccountStatements_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/statements/{StatementId}": {
      "get": {
        "tags": ["v2.0-Statements"],
        "summary": "Get Statement",
        "description": "Get Statement related to an account",
        "operationId": "getAccountStatement_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/statements/{StatementId}/file": {
      "get": {
        "tags": ["v2.0-Statements"],
        "summary": "Get Statement File",
        "description": "Get Statement File related to an account",
        "operationId": "getAccountStatementFile_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/statements/{StatementId}/transactions": {
      "get": {
        "tags": ["v2.0-Transactions"],
        "summary": "Get Statement Transactions",
        "description": "Get Statement Transactions related to an account",
        "operationId": "getAccountStatementTransactions_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/accounts/{AccountId}/transactions": {
      "get": {
        "tags": ["v2.0-Transactions"],
        "summary": "Get Account Transactions",
        "description": "Get transactions related to an account",
        "operationId": "getAccountTransactionsUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/balances": {
      "get": {
        "tags": ["v2.0-Balances"],
        "summary": "Get Balances",
        "description": "Get Balances",
        "operationId": "getBalancesUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/beneficiaries": {
      "get": {
        "tags": ["v2.0-Beneficiaries"],
        "summary": "Get Beneficiaries",
        "description": "Get Beneficiaries",
        "operationId": "getBeneficiariesUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/direct-debits": {
      "get": {
        "tags": ["v2.0-Direct-Debits"],
        "summary": "Get Direct Debits",
        "description": "Get Direct Debits",
        "operationId": "getDirectDebitsUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/offers": {
      "get": {
        "tags": ["v2.0-Offers"],
        "summary": "Get Offers",
        "description": "Get Offers",
        "operationId": "getOffers_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/party": {
      "get": {
        "tags": ["v2.0-Party"],
        "summary": "Get Party",
        "description": "Get Party",
        "operationId": "getParty_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/payment-submissions": {
      "post": {
        "tags": ["v2.0-Payments"],
        "summary": "Create a payment submission",
        "description": "Submit a previously setup payment",
        "operationId": "createPaymentSubmissionUsingPOST",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/payment-submissions/{PaymentSubmissionId}": {
      "get": {
        "tags": ["v2.0-Payments"],
        "summary": "Get a payment submission",
        "description": "Get payment submission",
        "operationId": "getPaymentSubmissionUsingGET",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }, { "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/payments": {
      "post": {
        "tags": ["v2.0-Payments"],
        "summary": "Create a single immediate payment",
        "description": "Create a single immediate payment",
        "operationId": "createSingleImmediatePaymentUsingPOST_1",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/payments/{PaymentId}": {
      "get": {
        "tags": ["v2.0-Payments"],
        "summary": "Get a single immediate payment",
        "description": "Get a single immediate payment",
        "operationId": "getSingleImmediatePaymentUsingGET_1",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }, { "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/products": {
      "get": {
        "tags": ["v2.0-Products"],
        "summary": "Get Products",
        "description": "Get Products",
        "operationId": "getProductsUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/scheduled-payments": {
      "get": {
        "tags": ["v2.0-Scheduled-Payments"],
        "summary": "Get Scheduled Payments",
        "description": "Get Scheduled Payments",
        "operationId": "getScheduledPayments_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/standing-orders": {
      "get": {
        "tags": ["v2.0-Standing-Orders"],
        "summary": "Get Standing Orders",
        "description": "Get Standing Orders",
        "operationId": "getStandingOrdersUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/statements": {
      "get": {
        "tags": ["v2.0-Statements"],
        "summary": "Get Statements",
        "description": "Get Statements",
        "operationId": "getStatements_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v2.0/transactions": {
      "get": {
        "tags": ["v2.0-Transactions"],
        "summary": "Get Transactions",
        "description": "Get Transactions",
        "operationId": "getTransactionsUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/account-access-consents": {
      "post": {
        "tags": ["v3.0-account-access-consents"],
        "summary": "Create an account access consent",
        "description": "Create an account access consent",
        "operationId": "createAccountAccessConsentsUsingPOST_1",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/account-access-consents/{ConsentId}": {
      "get": {
        "tags": ["v3.0-account-access-consents"],
        "summary": "Get an account access consent",
        "description": "Get an account access consent",
        "operationId": "getAccountAccessConsentsConsentUsingGET_1",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      },
      "delete": {
        "tags": ["v3.0-account-access-consents"],
        "summary": "Delete an account Access Consent",
        "description": "Delete an account Access Consent",
        "operationId": "deleteAccountAccessConsentUsingDELETE_1",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts": {
      "get": {
        "tags": ["v3.0-Accounts"],
        "summary": "Get Accounts",
        "description": "Get a list of accounts",
        "operationId": "getAccountsUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}": {
      "get": {
        "tags": ["v3.0-Accounts"],
        "summary": "Get Account",
        "description": "Get an account",
        "operationId": "getAccountUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/balances": {
      "get": {
        "tags": ["v1.1-Balances", "v3.0-Balances"],
        "summary": "Get Account Balances",
        "description": "Get Balances related to an account",
        "operationId": "getAccountBalancesUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/beneficiaries": {
      "get": {
        "tags": ["v3.0-Beneficiaries"],
        "summary": "Get Account Beneficiaries",
        "description": "Get Beneficiaries related to an account",
        "operationId": "getAccountBeneficiariesUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/direct-debits": {
      "get": {
        "tags": ["v1.1-Direct-Debits", "v3.0-Direct-Debits"],
        "summary": "Get Account Direct Debits",
        "description": "Get Direct Debits related to an account",
        "operationId": "getAccountDirectDebitsUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/offers": {
      "get": {
        "tags": ["v3.0-Offers"],
        "summary": "Get Account Offers",
        "description": "Get Offers related to an account",
        "operationId": "getAccountOffers_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/party": {
      "get": {
        "tags": ["v3.0-Party"],
        "summary": "Get Account Party",
        "description": "Get Party related to an account",
        "operationId": "getAccountParty",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/product": {
      "get": {
        "tags": ["v3.0-Products"],
        "summary": "Get Account Product",
        "description": "Get Product related to an account",
        "operationId": "getAccountProductUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/scheduled-payments": {
      "get": {
        "tags": ["v3.0-Scheduled-Payments"],
        "summary": "Get Account Scheduled Payments",
        "description": "Get Scheduled Payments related to an account",
        "operationId": "getAccountScheduledPayments",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/standing-orders": {
      "get": {
        "tags": ["v3.0-Standing-Orders"],
        "summary": "Get Account Standing Orders",
        "description": "Get Standing Orders related to an account",
        "operationId": "getAccountStandingOrdersUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/statements": {
      "get": {
        "tags": ["v3.0-Statements"],
        "summary": "Get Account Statements",
        "description": "Get Statements related to an account",
        "operationId": "getAccountStatements_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/statements/{StatementId}": {
      "get": {
        "tags": ["v3.0-Statements"],
        "summary": "Get Statement",
        "description": "Get Statement related to an account",
        "operationId": "getAccountStatement_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/statements/{StatementId}/file": {
      "get": {
        "tags": ["v3.0-Statements"],
        "summary": "Get Statement File",
        "description": "Get Statement File related to an account",
        "operationId": "getAccountStatementFile_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/statements/{StatementId}/transactions": {
      "get": {
        "tags": ["v2.0-Transactions", "v3.0-Transactions"],
        "summary": "Get Statement Transactions",
        "description": "Get Statement Transactions related to an account",
        "operationId": "getAccountStatementTransactions_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/accounts/{AccountId}/transactions": {
      "get": {
        "tags": ["v3.0-Transactions"],
        "summary": "Get Account Transactions",
        "description": "Get transactions related to an account",
        "operationId": "getAccountTransactionsUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/balances": {
      "get": {
        "tags": ["v3.0-Balances"],
        "summary": "Get Balances",
        "description": "Get Balances",
        "operationId": "getBalancesUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/beneficiaries": {
      "get": {
        "tags": ["v3.0-Beneficiaries"],
        "summary": "Get Beneficiaries",
        "description": "Get Beneficiaries",
        "operationId": "getBeneficiariesUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/callback-urls": {
      "get": {
        "tags": ["Callback URLs"],
        "summary": "Read all callback URLs",
        "operationId": "readCallbackUrls_1",
        "security": [{ "TPPOAuth2Security": ["accounts", "payments", "fundsconfirmations"] }],
        "deprecated": false
      },
      "post": {
        "tags": ["Callback URLs"],
        "summary": "Create a callback URL",
        "operationId": "createCallbackURL_1",
        "security": [{ "TPPOAuth2Security": ["accounts", "payments", "fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/callback-urls/{CallbackUrlId}": {
      "put": {
        "tags": ["Callback URLs"],
        "summary": "Amend a callback URI",
        "operationId": "amendCallbackURL_1",
        "security": [{ "TPPOAuth2Security": ["accounts", "payments", "fundsconfirmations"] }],
        "deprecated": false
      },
      "delete": {
        "tags": ["Callback URLs"],
        "summary": "Delete a callback URI",
        "operationId": "deleteCallbackURL_1",
        "security": [{ "TPPOAuth2Security": ["accounts", "payments", "fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/direct-debits": {
      "get": {
        "tags": ["v3.0-Direct-Debits"],
        "summary": "Get Direct Debits",
        "description": "Get Direct Debits",
        "operationId": "getDirectDebitsUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-payment-consents": {
      "post": {
        "tags": ["Domestic Payments"],
        "summary": "Create Domestic Payment Consents",
        "operationId": "createDomesticPaymentConsents",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-payment-consents/{ConsentId}": {
      "get": {
        "tags": ["Domestic Payments"],
        "summary": "Get Domestic Payment Consents",
        "operationId": "getDomesticPaymentConsentsConsentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-payments": {
      "post": {
        "tags": ["Domestic Payments"],
        "summary": "Create Domestic Payments",
        "operationId": "createDomesticPayments",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-payments/{DomesticPaymentId}": {
      "get": {
        "tags": ["Domestic Payments"],
        "summary": "Get Domestic Payments",
        "operationId": "getDomesticPaymentsDomesticPaymentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-scheduled-payment-consents": {
      "post": {
        "tags": ["Domestic Scheduled Payments"],
        "summary": "Create Domestic Scheduled Payment Consents",
        "operationId": "createDomesticScheduledPaymentConsents",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-scheduled-payment-consents/{ConsentId}": {
      "get": {
        "tags": ["Domestic Scheduled Payments"],
        "summary": "Get Domestic Scheduled Payment Consents",
        "operationId": "getDomesticScheduledPaymentConsentsConsentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-scheduled-payments": {
      "post": {
        "tags": ["Domestic Scheduled Payments"],
        "summary": "Create Domestic Scheduled Payments",
        "operationId": "createDomesticScheduledPayments",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-scheduled-payments/{DomesticScheduledPaymentId}": {
      "get": {
        "tags": ["Domestic Scheduled Payments"],
        "summary": "Get Domestic Scheduled Payments",
        "operationId": "getDomesticScheduledPaymentsDomesticScheduledPaymentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-standing-order-consents": {
      "post": {
        "tags": ["Domestic Standing Orders"],
        "summary": "Create Domestic Standing Order Consents",
        "operationId": "createDomesticStandingOrderConsents",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-standing-order-consents/{ConsentId}": {
      "get": {
        "tags": ["Domestic Standing Orders"],
        "summary": "Get Domestic Standing Order Consents",
        "operationId": "getDomesticStandingOrderConsentsConsentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-standing-orders": {
      "post": {
        "tags": ["Domestic Standing Orders"],
        "summary": "Create Domestic Standing Orders",
        "operationId": "createDomesticStandingOrders_1",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/domestic-standing-orders/{DomesticStandingOrderId}": {
      "get": {
        "tags": ["Domestic Standing Orders"],
        "summary": "Get Domestic Standing Orders",
        "operationId": "getDomesticStandingOrdersDomesticStandingOrderId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/file-payment-consents": {
      "post": {
        "tags": ["File Payments"],
        "summary": "Create File Payment Consents",
        "operationId": "createFilePaymentConsents_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/file-payment-consents/{ConsentId}": {
      "get": {
        "tags": ["File Payments"],
        "summary": "Get File Payment Consents",
        "operationId": "getFilePaymentConsentsConsentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/file-payment-consents/{ConsentId}/file": {
      "get": {
        "tags": ["File Payments"],
        "summary": "Get File Payment Consents",
        "operationId": "getFilePaymentConsentsConsentIdFile_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      },
      "post": {
        "tags": ["File Payments"],
        "summary": "Create File Payment Consents",
        "operationId": "createFilePaymentConsentsConsentIdFile_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/file-payments": {
      "post": {
        "tags": ["File Payments"],
        "summary": "Create File Payments",
        "operationId": "createFilePayments",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/file-payments/{FilePaymentId}": {
      "get": {
        "tags": ["File Payments"],
        "summary": "Get File Payments",
        "operationId": "getFilePaymentsFilePaymentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/file-payments/{FilePaymentId}/report-file": {
      "get": {
        "tags": ["File Payments"],
        "summary": "Get File Payments",
        "operationId": "getFilePaymentsFilePaymentIdReportFile",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/funds-confirmation-consents": {
      "post": {
        "tags": ["Funds Confirmation"],
        "summary": "Create Funds Confirmation Consents",
        "operationId": "createFundsConfirmationConsents_1",
        "security": [{ "TPPOAuth2Security": ["fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/funds-confirmation-consents/{ConsentId}": {
      "get": {
        "tags": ["Funds Confirmation"],
        "summary": "Get Funds Confirmation Consents",
        "operationId": "getFundsConfirmationConsentsConsentId_1",
        "security": [{ "TPPOAuth2Security": ["fundsconfirmations"] }],
        "deprecated": false
      },
      "delete": {
        "tags": ["Funds Confirmation"],
        "summary": "Delete Funds Confirmation Consents",
        "operationId": "deleteFundsConfirmationConsentsConsentId_1",
        "security": [{ "TPPOAuth2Security": ["fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/funds-confirmations": {
      "post": {
        "tags": ["Funds Confirmation"],
        "summary": "Create Funds Confirmation",
        "operationId": "createFundsConfirmation_1",
        "security": [{ "TPPOAuth2Security": ["fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/funds-confirmations/{FundsConfirmationId}": {
      "get": {
        "tags": ["Funds Confirmation"],
        "summary": "Get Funds Confirmation",
        "operationId": "getFundsConfirmationId_1",
        "security": [{ "TPPOAuth2Security": ["fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-payment-consents": {
      "post": {
        "tags": ["International Payments"],
        "summary": "Create International Payment Consents",
        "operationId": "createInternationalPaymentConsents_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-payment-consents/{ConsentId}": {
      "get": {
        "tags": ["International Payments"],
        "summary": "Get International Payment Consents",
        "operationId": "getInternationalPaymentConsentsConsentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-payments": {
      "post": {
        "tags": ["International Payments"],
        "summary": "Create International Payments",
        "operationId": "createInternationalPayments_1",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-payments/{InternationalPaymentId}": {
      "get": {
        "tags": ["International Payments"],
        "summary": "Get International Payments",
        "operationId": "getInternationalPaymentsInternationalPaymentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-scheduled-payment-consents": {
      "post": {
        "tags": ["International Scheduled Payments"],
        "summary": "Create International Scheduled Payment Consents",
        "operationId": "createInternationalScheduledPaymentConsents_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-scheduled-payment-consents/{ConsentId}": {
      "get": {
        "tags": ["International Scheduled Payments"],
        "summary": "Get International Scheduled Payment Consents",
        "operationId": "getInternationalScheduledPaymentConsentsConsentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-scheduled-payments": {
      "post": {
        "tags": ["International Scheduled Payments"],
        "summary": "Create International Scheduled Payments",
        "operationId": "createInternationalScheduledPayments_1",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-scheduled-payments/{InternationalScheduledPaymentId}": {
      "get": {
        "tags": ["International Scheduled Payments"],
        "summary": "Get International Scheduled Payments",
        "operationId": "getInternationalScheduledPaymentsInternationalScheduledPaymentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-standing-order-consents": {
      "post": {
        "tags": ["International Standing Orders"],
        "summary": "Create International Standing Order Consents",
        "operationId": "createInternationalStandingOrderConsents",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-standing-order-consents/{ConsentId}": {
      "get": {
        "tags": ["International Standing Orders"],
        "summary": "Get International Standing Order Consents",
        "operationId": "getInternationalStandingOrderConsentsConsentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-standing-orders": {
      "post": {
        "tags": ["International Standing Orders"],
        "summary": "Create International Standing Orders",
        "operationId": "createInternationalStandingOrders_1",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/international-standing-orders/{InternationalStandingOrderPaymentId}": {
      "get": {
        "tags": ["International Standing Orders"],
        "summary": "Get International Standing Orders",
        "operationId": "getInternationalStandingOrdersInternationalStandingOrderPaymentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/offers": {
      "get": {
        "tags": ["v3.0-Offers"],
        "summary": "Get Offers",
        "description": "Get Offers",
        "operationId": "getOffers_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/party": {
      "get": {
        "tags": ["v3.0-Party"],
        "summary": "Get Party",
        "description": "Get Party",
        "operationId": "getParty",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/products": {
      "get": {
        "tags": ["v3.0-Products"],
        "summary": "Get Products",
        "description": "Get Products",
        "operationId": "getProductsUsingGET",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/scheduled-payments": {
      "get": {
        "tags": ["v3.0-Scheduled-Payments"],
        "summary": "Get Scheduled Payments",
        "description": "Get Scheduled Payments",
        "operationId": "getScheduledPayments",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/standing-orders": {
      "get": {
        "tags": ["v3.0-Standing-Orders"],
        "summary": "Get Standing Orders",
        "description": "Get Standing Orders",
        "operationId": "getStandingOrdersUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/statements": {
      "get": {
        "tags": ["v3.0-Statements"],
        "summary": "Get Statements",
        "description": "Get Statements",
        "operationId": "getStatements_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.0/transactions": {
      "get": {
        "tags": ["v3.0-Transactions"],
        "summary": "Get Transactions",
        "description": "Get Transactions",
        "operationId": "getTransactionsUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/account-access-consents": {
      "post": {
        "tags": ["v3.1-account-access-consents"],
        "summary": "Create an account access consent",
        "description": "Create an account access consent",
        "operationId": "createAccountAccessConsentsUsingPOST",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/account-access-consents/{ConsentId}": {
      "get": {
        "tags": ["v3.1-account-access-consents"],
        "summary": "Get an account access consent",
        "description": "Get an account access consent",
        "operationId": "getAccountAccessConsentsConsentUsingGET",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      },
      "delete": {
        "tags": ["v3.1-account-access-consents"],
        "summary": "Delete an account Access Consent",
        "description": "Delete an account Access Consent",
        "operationId": "deleteAccountAccessConsentUsingDELETE",
        "security": [{ "TPPOAuth2Security": ["tpp_client_credential"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts": {
      "get": {
        "tags": ["v3.1-Accounts"],
        "summary": "Get Accounts",
        "description": "Get a list of accounts",
        "operationId": "getAccountsUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}": {
      "get": {
        "tags": ["v3.1-Accounts"],
        "summary": "Get Account",
        "description": "Get an account",
        "operationId": "getAccountUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/balances": {
      "get": {
        "tags": ["v1.1-Balances", "v3.1-Balances"],
        "summary": "Get Account Balances",
        "description": "Get Balances related to an account",
        "operationId": "getAccountBalancesUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/beneficiaries": {
      "get": {
        "tags": ["v3.1-Beneficiaries"],
        "summary": "Get Account Beneficiaries",
        "description": "Get Beneficiaries related to an account",
        "operationId": "getAccountBeneficiariesUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/direct-debits": {
      "get": {
        "tags": ["v1.1-Direct-Debits", "v3.1-Direct-Debits"],
        "summary": "Get Account Direct Debits",
        "description": "Get Direct Debits related to an account",
        "operationId": "getAccountDirectDebitsUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/offers": {
      "get": {
        "tags": ["v3.1-Offers"],
        "summary": "Get Account Offers",
        "description": "Get Offers related to an account",
        "operationId": "getAccountOffers",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/party": {
      "get": {
        "tags": ["v3.1-Party"],
        "summary": "Get Account Party",
        "description": "Get Party related to an account",
        "operationId": "getAccountParty_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/product": {
      "get": {
        "tags": ["v3.1-Products"],
        "summary": "Get Account Product",
        "description": "Get Product related to an account",
        "operationId": "getAccountProductUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/scheduled-payments": {
      "get": {
        "tags": ["v3.1-Scheduled-Payments"],
        "summary": "Get Account Scheduled Payments",
        "description": "Get Scheduled Payments related to an account",
        "operationId": "getAccountScheduledPayments_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/standing-orders": {
      "get": {
        "tags": ["v3.1-Standing-Orders"],
        "summary": "Get Account Standing Orders",
        "description": "Get Standing Orders related to an account",
        "operationId": "getAccountStandingOrdersUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/statements": {
      "get": {
        "tags": ["v3.1-Statements"],
        "summary": "Get Account Statements",
        "description": "Get Statements related to an account",
        "operationId": "getAccountStatements",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/statements/{StatementId}": {
      "get": {
        "tags": ["v3.1-Statements"],
        "summary": "Get Statement",
        "description": "Get Statement related to an account",
        "operationId": "getAccountStatement",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/statements/{StatementId}/file": {
      "get": {
        "tags": ["v3.1-Statements"],
        "summary": "Get Statement File",
        "description": "Get Statement File related to an account",
        "operationId": "getAccountStatementFile",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/statements/{StatementId}/transactions": {
      "get": {
        "tags": ["v2.0-Transactions", "v3.1-Transactions"],
        "summary": "Get Statement Transactions",
        "description": "Get Statement Transactions related to an account",
        "operationId": "getAccountStatementTransactions",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/accounts/{AccountId}/transactions": {
      "get": {
        "tags": ["v3.1-Transactions"],
        "summary": "Get Account Transactions",
        "description": "Get transactions related to an account",
        "operationId": "getAccountTransactionsUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/balances": {
      "get": {
        "tags": ["v3.1-Balances"],
        "summary": "Get Balances",
        "description": "Get Balances",
        "operationId": "getBalancesUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/beneficiaries": {
      "get": {
        "tags": ["v3.1-Beneficiaries"],
        "summary": "Get Beneficiaries",
        "description": "Get Beneficiaries",
        "operationId": "getBeneficiariesUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/callback-urls": {
      "get": {
        "tags": ["Callback URLs"],
        "summary": "Read all callback URLs",
        "operationId": "readCallbackUrls",
        "security": [{ "TPPOAuth2Security": ["accounts", "payments", "fundsconfirmations"] }],
        "deprecated": false
      },
      "post": {
        "tags": ["Callback URLs"],
        "summary": "Create a callback URL",
        "operationId": "createCallbackURL",
        "security": [{ "TPPOAuth2Security": ["accounts", "payments", "fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/callback-urls/{CallbackUrlId}": {
      "put": {
        "tags": ["Callback URLs"],
        "summary": "Amend a callback URI",
        "operationId": "amendCallbackURL",
        "security": [{ "TPPOAuth2Security": ["accounts", "payments", "fundsconfirmations"] }],
        "deprecated": false
      },
      "delete": {
        "tags": ["Callback URLs"],
        "summary": "Delete a callback URI",
        "operationId": "deleteCallbackURL",
        "security": [{ "TPPOAuth2Security": ["accounts", "payments", "fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/direct-debits": {
      "get": {
        "tags": ["v3.1-Direct-Debits"],
        "summary": "Get Direct Debits",
        "description": "Get Direct Debits",
        "operationId": "getDirectDebitsUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-payment-consents": {
      "post": {
        "tags": ["Domestic Payments"],
        "summary": "Create Domestic Payment Consents",
        "operationId": "createDomesticPaymentConsents_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-payment-consents/{ConsentId}": {
      "get": {
        "tags": ["Domestic Payments"],
        "summary": "Get Domestic Payment Consents",
        "operationId": "getDomesticPaymentConsentsConsentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-payment-consents/{ConsentId}/funds-confirmation": {
      "get": {
        "tags": ["domestic-payment-consents-api-controller"],
        "summary": "Get Domestic Payment Consents Funds Confirmation",
        "operationId": "getDomesticPaymentConsentsConsentIdFundsConfirmation",
        "security": [{ "PSUOAuth2Security": [] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-payments": {
      "post": {
        "tags": ["Domestic Payments"],
        "summary": "Create Domestic Payments",
        "operationId": "createDomesticPayments_1",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-payments/{DomesticPaymentId}": {
      "get": {
        "tags": ["Domestic Payments"],
        "summary": "Get Domestic Payments",
        "operationId": "getDomesticPaymentsDomesticPaymentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-scheduled-payment-consents": {
      "post": {
        "tags": ["Domestic Scheduled Payments"],
        "summary": "Create Domestic Scheduled Payment Consents",
        "operationId": "createDomesticScheduledPaymentConsents_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-scheduled-payment-consents/{ConsentId}": {
      "get": {
        "tags": ["Domestic Scheduled Payments"],
        "summary": "Get Domestic Scheduled Payment Consents",
        "operationId": "getDomesticScheduledPaymentConsentsConsentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-scheduled-payments": {
      "post": {
        "tags": ["Domestic Scheduled Payments"],
        "summary": "Create Domestic Scheduled Payments",
        "operationId": "createDomesticScheduledPayments_1",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-scheduled-payments/{DomesticScheduledPaymentId}": {
      "get": {
        "tags": ["Domestic Scheduled Payments"],
        "summary": "Get Domestic Scheduled Payments",
        "operationId": "getDomesticScheduledPaymentsDomesticScheduledPaymentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-standing-order-consents": {
      "post": {
        "tags": ["Domestic Standing Orders"],
        "summary": "Create Domestic Standing Order Consents",
        "operationId": "createDomesticStandingOrderConsents_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-standing-order-consents/{ConsentId}": {
      "get": {
        "tags": ["Domestic Standing Orders"],
        "summary": "Get Domestic Standing Order Consents",
        "operationId": "getDomesticStandingOrderConsentsConsentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-standing-orders": {
      "post": {
        "tags": ["Domestic Standing Orders"],
        "summary": "Create Domestic Standing Orders",
        "operationId": "createDomesticStandingOrders",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/domestic-standing-orders/{DomesticStandingOrderId}": {
      "get": {
        "tags": ["Domestic Standing Orders"],
        "summary": "Get Domestic Standing Orders",
        "operationId": "getDomesticStandingOrdersDomesticStandingOrderId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/file-payment-consents": {
      "post": {
        "tags": ["File Payments"],
        "summary": "Create File Payment Consents",
        "operationId": "createFilePaymentConsents",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/file-payment-consents/{ConsentId}": {
      "get": {
        "tags": ["File Payments"],
        "summary": "Get File Payment Consents",
        "operationId": "getFilePaymentConsentsConsentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/file-payment-consents/{ConsentId}/file": {
      "get": {
        "tags": ["File Payments"],
        "summary": "Get File Payment Consents",
        "operationId": "getFilePaymentConsentsConsentIdFile",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      },
      "post": {
        "tags": ["File Payments"],
        "summary": "Create File Payment Consents",
        "operationId": "createFilePaymentConsentsConsentIdFile",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/file-payments": {
      "post": {
        "tags": ["File Payments"],
        "summary": "Create File Payments",
        "operationId": "createFilePayments_1",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/file-payments/{FilePaymentId}": {
      "get": {
        "tags": ["File Payments"],
        "summary": "Get File Payments",
        "operationId": "getFilePaymentsFilePaymentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/file-payments/{FilePaymentId}/report-file": {
      "get": {
        "tags": ["File Payments"],
        "summary": "Get File Payments",
        "operationId": "getFilePaymentsFilePaymentIdReportFile_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/funds-confirmation-consents": {
      "post": {
        "tags": ["Funds Confirmation"],
        "summary": "Create Funds Confirmation Consents",
        "operationId": "createFundsConfirmationConsents",
        "security": [{ "TPPOAuth2Security": ["fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/funds-confirmation-consents/{ConsentId}": {
      "get": {
        "tags": ["Funds Confirmation"],
        "summary": "Get Funds Confirmation Consents",
        "operationId": "getFundsConfirmationConsentsConsentId",
        "security": [{ "TPPOAuth2Security": ["fundsconfirmations"] }],
        "deprecated": false
      },
      "delete": {
        "tags": ["Funds Confirmation"],
        "summary": "Delete Funds Confirmation Consents",
        "operationId": "deleteFundsConfirmationConsentsConsentId",
        "security": [{ "TPPOAuth2Security": ["fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/funds-confirmations": {
      "post": {
        "tags": ["Funds Confirmation"],
        "summary": "Create Funds Confirmation",
        "operationId": "createFundsConfirmation",
        "security": [{ "TPPOAuth2Security": ["fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/funds-confirmations/{FundsConfirmationId}": {
      "get": {
        "tags": ["Funds Confirmation"],
        "summary": "Get Funds Confirmation",
        "operationId": "getFundsConfirmationId",
        "security": [{ "TPPOAuth2Security": ["fundsconfirmations"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-payment-consents": {
      "post": {
        "tags": ["International Payments"],
        "summary": "Create International Payment Consents",
        "operationId": "createInternationalPaymentConsents",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-payment-consents/{ConsentId}": {
      "get": {
        "tags": ["International Payments"],
        "summary": "Get International Payment Consents",
        "operationId": "getInternationalPaymentConsentsConsentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-payment-consents/{ConsentId}/funds-confirmation": {
      "get": {
        "tags": ["international-payment-consents-api-controller"],
        "summary": "Get International Payment Consents Funds Confirmation",
        "operationId": "getInternationalPaymentConsentsConsentIdFundsConfirmation",
        "security": [{ "PSUOAuth2Security": [] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-payments": {
      "post": {
        "tags": ["International Payments"],
        "summary": "Create International Payments",
        "operationId": "createInternationalPayments",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-payments/{InternationalPaymentId}": {
      "get": {
        "tags": ["International Payments"],
        "summary": "Get International Payments",
        "operationId": "getInternationalPaymentsInternationalPaymentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-scheduled-payment-consents": {
      "post": {
        "tags": ["International Scheduled Payments"],
        "summary": "Create International Scheduled Payment Consents",
        "operationId": "createInternationalScheduledPaymentConsents",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-scheduled-payment-consents/{ConsentId}": {
      "get": {
        "tags": ["International Scheduled Payments"],
        "summary": "Get International Scheduled Payment Consents",
        "operationId": "getInternationalScheduledPaymentConsentsConsentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-scheduled-payment-consents/{ConsentId}/funds-confirmation": {
      "get": {
        "tags": ["international-scheduled-payment-consents-api-controller"],
        "summary": "Get International Scheduled Payment Consents Funds Confirmation",
        "operationId": "getInternationalScheduledPaymentConsentsConsentIdFundsConfirmation",
        "security": [{ "PSUOAuth2Security": [] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-scheduled-payments": {
      "post": {
        "tags": ["International Scheduled Payments"],
        "summary": "Create International Scheduled Payments",
        "operationId": "createInternationalScheduledPayments",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-scheduled-payments/{InternationalScheduledPaymentId}": {
      "get": {
        "tags": ["International Scheduled Payments"],
        "summary": "Get International Scheduled Payments",
        "operationId": "getInternationalScheduledPaymentsInternationalScheduledPaymentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-standing-order-consents": {
      "post": {
        "tags": ["International Standing Orders"],
        "summary": "Create International Standing Order Consents",
        "operationId": "createInternationalStandingOrderConsents_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-standing-order-consents/{ConsentId}": {
      "get": {
        "tags": ["International Standing Orders"],
        "summary": "Get International Standing Order Consents",
        "operationId": "getInternationalStandingOrderConsentsConsentId_1",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-standing-orders": {
      "post": {
        "tags": ["International Standing Orders"],
        "summary": "Create International Standing Orders",
        "operationId": "createInternationalStandingOrders",
        "security": [{ "PSUOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/international-standing-orders/{InternationalStandingOrderPaymentId}": {
      "get": {
        "tags": ["International Standing Orders"],
        "summary": "Get International Standing Orders",
        "operationId": "getInternationalStandingOrdersInternationalStandingOrderPaymentId",
        "security": [{ "TPPOAuth2Security": ["payments"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/offers": {
      "get": {
        "tags": ["v3.1-Offers"],
        "summary": "Get Offers",
        "description": "Get Offers",
        "operationId": "getOffers",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/party": {
      "get": {
        "tags": ["v3.1-Party"],
        "summary": "Get Party",
        "description": "Get Party",
        "operationId": "getParty_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/products": {
      "get": {
        "tags": ["v3.1-Products"],
        "summary": "Get Products",
        "description": "Get Products",
        "operationId": "getProductsUsingGET_3",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/scheduled-payments": {
      "get": {
        "tags": ["v3.1-Scheduled-Payments"],
        "summary": "Get Scheduled Payments",
        "description": "Get Scheduled Payments",
        "operationId": "getScheduledPayments_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/standing-orders": {
      "get": {
        "tags": ["v3.1-Standing-Orders"],
        "summary": "Get Standing Orders",
        "description": "Get Standing Orders",
        "operationId": "getStandingOrdersUsingGET_2",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/statements": {
      "get": {
        "tags": ["v3.1-Statements"],
        "summary": "Get Statements",
        "description": "Get Statements",
        "operationId": "getStatements",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    },
    "/open-banking/v3.1/transactions": {
      "get": {
        "tags": ["v3.1-Transactions"],
        "summary": "Get Transactions",
        "description": "Get Transactions",
        "operationId": "getTransactionsUsingGET_1",
        "security": [{ "PSUOAuth2Security": ["accounts"] }],
        "deprecated": false
      }
    }
  }
}
