name: Build-UI

on: [push]

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Prepare customers
        working-directory: ./forgerock-openbanking-ui
        run: |
          git clone https://$GITHUB_ACCESS_TOKEN@github.com/ForgeCloud/ob-customers.git customers
          cp -r ./customers/lloyds ./customers/hl ./customers/westpac ./customers/jpmorgan ./customers/citibank ./customers/suncorp themes/
          ls -la ./themes
          rm -fr customers
      - name: Prepare versionning
        working-directory: ./forgerock-openbanking-ui
        run: |
          echo "::set-env name=PROJECT_VERSION::$(jq -r ".project_version" package.json)'"
          echo "::set-env name=BUILD_VERSION::$PROJECT_VERSION-$GITHUB_SHA"
          echo $PROJECT_VERSION
          echo $BUILD_VERSION
      - name: Install Dependencies
        working-directory: ./forgerock-openbanking-ui
        run: |
          npm ci
          npm run test.ci
          ./node_modules/@angular/cli/bin/ng lint
  build_auth:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build & Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: "obri/auth:$BUILD_VERSION"
          workdir: ./forgerock-openbanking-ui
          dockerfile: projects/auth/docker/Dockerfile
          registry: r.cfcr.io
          username: ${{ secrets.CODEFRESH_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.CODEFRESH_DOCKER_REGISTRY_API_KEY }}
  build_swagger:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build & Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: "obri/swagger-ui:$BUILD_VERSION"
          workdir: ./forgerock-openbanking-ui
          dockerfile: projects/swagger/docker/Dockerfile
          registry: r.cfcr.io
          username: ${{ secrets.CODEFRESH_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.CODEFRESH_DOCKER_REGISTRY_API_KEY }}
