name: Build-UI

on: [push]

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Prepare customers
        working-directory: ./forgerock-openbanking-ui
        run: |
          git clone https://$GITHUB_ACCESS_TOKEN@github.com/ForgeCloud/ob-customers.git customers
          cp -r ./customers/lloyds ./customers/hl ./customers/westpac ./customers/jpmorgan ./customers/citibank ./customers/suncorp themes/
          ls -la ./themes
          rm -fr customers
      - name: Run tests
        working-directory: ./forgerock-openbanking-ui
        run: |
          npm ci
          npm run test.ci
          ./node_modules/@angular/cli/bin/ng lint
      - name: Build auth docker image
        working-directory: ./forgerock-openbanking-ui
        run: |
          export BUILD_VERSION=$(jq -r ".project_version" package.json)-${GITHUB_SHA::7}
          echo "Building docker image r.cfcr.io/openbanking/obri/auth:${BUILD_VERSION}"
          docker login r.cfcr.io -u fropenbanking -p ${{ secrets.CODEFRESH_DOCKER_REGISTRY_API_KEY }}
          docker build -f projects/auth/docker/Dockerfile -t r.cfcr.io/openbanking/obri/auth:$BUILD_VERSION forgerock-openbanking-ui
          docker push r.cfcr.io/openbanking/obri/auth:$BUILD_VERSION
      - name: Build swagger docker image
        working-directory: ./forgerock-openbanking-ui
        run: |
          export BUILD_VERSION=$(jq -r ".project_version" package.json)-${GITHUB_SHA::7}
          echo "Building docker image r.cfcr.io/openbanking/obri/swagger-ui:$BUILD_VERSION"
          docker login r.cfcr.io -u fropenbanking -p ${{ secrets.CODEFRESH_DOCKER_REGISTRY_API_KEY }}
          docker build -f projects/swagger/docker/Dockerfile -t r.cfcr.io/openbanking/obri/swagger-ui:$BUILD_VERSION forgerock-openbanking-ui
          docker push r.cfcr.io/openbanking/obri/swagger-ui:$BUILD_VERSION